/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugaskelompokpbo;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author ASUS
 */
public class HomePage extends javax.swing.JFrame {
    // membuat properti conn, res, pst 
    public Connection conn=null;
    public ResultSet res=null;
    public PreparedStatement pst=null;
    /**
     * Creates new form MainMenu
     */
    public HomePage() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, 
        size.height/2 - getHeight()/2);
        currentDateTime();
    }

    // Untuk menampilkan tanggal dan waktu saat ini 
    public void currentDateTime (){
        
        Calendar cal =new GregorianCalendar();
        int bulan = cal.get(Calendar.MONTH);
        int tahun = cal.get(Calendar.YEAR);
        int hari = cal.get(Calendar.DAY_OF_MONTH);

        text_date.setText(hari+"-"+(bulan+1)+"-"+tahun);
        
        int detik = cal.get(Calendar.SECOND);
        int menit = cal.get(Calendar.MINUTE);
        int jam = cal.get(Calendar.HOUR);
        
        text_time.setText(jam+":"+(menit)+":"+detik);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        btn_mhs = new javax.swing.JButton();
        btn_matkul = new javax.swing.JButton();
        btn_dosen = new javax.swing.JButton();
        btn_user = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        text_date = new javax.swing.JMenu();
        text_time = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 51));
        jPanel1.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setText("SELAMAT DATANG ADMIN");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(210, 50, 510, 60);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("SISTEM INFORMASI AKADEMIK");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 110, 590, 80);

        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Exit_26px_1.png"))); // NOI18N
        btn_logout.setText("Logout");
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_logoutMouseClicked(evt);
            }
        });
        jPanel1.add(btn_logout);
        btn_logout.setBounds(20, 440, 100, 50);

        btn_mhs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_People_50px.png"))); // NOI18N
        btn_mhs.setText("Data Mahasiswa");
        btn_mhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_mhsMouseClicked(evt);
            }
        });
        jPanel1.add(btn_mhs);
        btn_mhs.setBounds(460, 360, 170, 50);

        btn_matkul.setText("Data Matkul");
        btn_matkul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_matkulMouseClicked(evt);
            }
        });
        jPanel1.add(btn_matkul);
        btn_matkul.setBounds(320, 360, 120, 50);

        btn_dosen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_People_50px.png"))); // NOI18N
        btn_dosen.setText("Data Dosen");
        btn_dosen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dosenMouseClicked(evt);
            }
        });
        jPanel1.add(btn_dosen);
        btn_dosen.setBounds(460, 290, 170, 50);

        btn_user.setText("Data User");
        btn_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_userMouseClicked(evt);
            }
        });
        jPanel1.add(btn_user);
        btn_user.setBounds(320, 290, 120, 50);

        text_date.setText("Date");
        jMenuBar1.add(text_date);

        text_time.setText("Time");
        jMenuBar1.add(text_time);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 892, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_userMouseClicked
        // TODO add your handling code here:
        DataUser user = new DataUser();
        user.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_userMouseClicked

    private void btn_dosenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dosenMouseClicked
        // TODO add your handling code here:
        DataDosen dosen = new DataDosen();
        dosen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_dosenMouseClicked

    private void btn_mhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_mhsMouseClicked
        // TODO add your handling code here:
        DataMahasiswa mhs = new DataMahasiswa();
        mhs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_mhsMouseClicked

    private void btn_matkulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_matkulMouseClicked
        // TODO add your handling code here:
        DataMatkul matkul = new DataMatkul();
        matkul.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_matkulMouseClicked

    private void btn_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseClicked
        // TODO add your handling code here:
        Login logout = new Login();
        logout.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dosen;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_matkul;
    private javax.swing.JButton btn_mhs;
    private javax.swing.JButton btn_user;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu text_date;
    private javax.swing.JMenu text_time;
    // End of variables declaration//GEN-END:variables
}
